export const tokens = Object.freeze({
  color: {
    paper: "#F3F0E7",
    ink: "#242A27",
    muted: "#69736C",
    line: "#C5C8BC",
    accent: "#446557",
    negative: "#985F4C",
  },
  font: {
    headline: "Noto Serif KR",
    wordmark: "Prociono",
    date: "Instrument Serif",
    eyebrowEn: "Instrument Serif",
    eyebrowKo: "Chosun",
    caption: "Pretendard",
    captionLatin: "Editorial",
    quote: "Chosun",
    body: "Pretendard",
    number: "Instrument Serif",
    latin: "Instrument Serif",
  },
  safe: { left: 144, right: 192, top: 280, bottom: 220 },
  size: {
    headline: 86,
    body: 64,
    chartBody: 56,
    caption: 54,
    source: 25,
    label: 30,
    eyebrow: 24,
    date: 36,
    quote: 66,
    cover: 76,
  },
  visualText: { body: 60, label: 48, role: 28, quote: 50, unit: 56 },
  tracking: {
    wordmark: "-0.02em",
    date: "normal",
    headline: "-0.09em",
    caption: "-0.015em",
    body: "-0.02em",
    quote: "-0.02em",
    chart: "0.01em",
    chartKorean: "-0.02em",
  },
  weight: { headline: 600, caption: 600, body: 400, quote: 400 },
  layout: {
    contentWidth: 744,
    mastheadInset: 144,
    eyebrowTop: 370,
    headlineTop: 408,
    headlineHeight: 236,
    contentTop: 700,
    chartHeight: 420,
    chartLabelHeight: 44,
    chartLabelGap: 16,
    bodyGap: 24,
    bodyInset: 16,
    centralHeight: 620,
    portraitWidth: 280,
    portraitHeight: 500,
    portraitGap: 48,
    captionTop: 1396,
    captionHeight: 172,
    captionInset: 176,
    captionWidth: 728,
    sourceTop: 1620,
    sourceHeight: 70,
    sourceLineHeight: 1.35,
    sourceLeft: 350,
    sourceRight: 184,
  },
  audio: { sfxVolume: 0.4, sfxSourcePeakDb: -6 },
  brandmark: { src: "branding/macrogics-editorial.svg", size: 50, gap: 16 },
  motion: {
    enter: 18,
    offset: 12,
    chartReveal: 45,
    chartRipple: 30,
    chartRippleCycle: 45,
    chartHeadRadius: 6,
  },
});
